name: Autoblocks Replays

on: push

env:
  POETRY_VERSION: "1.5.1"
  PYTHON_VERSION: "3.11"

jobs:
  autoblocks-replays:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install

      - name: Start the app
        run: poetry run start &
        env:
          # Use the replay ingestion key so that Autoblocks knows we're sending replayed events
          AUTOBLOCKS_INGESTION_KEY: ${{ secrets.DEMO_AUTOBLOCKS_REPLAY_INGESTION_KEY }}

          # Any other environment variables the application needs to run
          OPENAI_API_KEY: ${{ secrets.DEMO_OPENAI_API_KEY }}

      - name: Wait for the app to be ready
        run: |
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:5000/health)" != "200" ]]; do sleep 1; done

     - name: Run static replays
       run: poetry run replay-static

      - name: Run dynamic replays
        run: poetry run replay-dynamic
        env:
          # Dynamic replays are fetched from the Autoblocks API
          AUTOBLOCKS_API_KEY: ${{ secrets.DEMO_AUTOBLOCKS_API_KEY }}

      - name: Show log file
        run: cat flask.log
